import type { BucketRequest } from './validate';

// Pure generator: request + context -> the exact stack files a human would
// hand-write (mirrors idp-gitops/stacks/dev/platform-demo/). No I/O here so it
// is trivially unit-tested; github.ts is the only side-effecting module.
//
// Templates are pre-aligned to `terraform fmt` output. The block keys are fixed,
// so the alignment is constant regardless of the (quoted) values — every
// generated stack is fmt-clean, which pr.yml's `fmt -check` requires.

// Fixed platform facts (match platform-demo; see CLAUDE.md "Current platform state").
const STATE_BUCKET = 'idp-prototype-edo-tfstate';
const PROJECT_ID = 'idp-prototype-edo';
const REGION = 'europe-west2';

export interface GenerateContext {
  requester: string;
  requestId: string;
  date: string; // YYYY-MM-DD
}

export interface GeneratedStack {
  stackDir: string; // repo-relative
  bucketName: string;
  files: Record<string, string>;
}

export function generate(req: BucketRequest, ctx: GenerateContext): GeneratedStack {
  const dirName = `${req.owning_team}-${req.name}`;
  const prefix = `stacks/${req.environment}/${dirName}`;
  const stackDir = `idp-gitops/${prefix}`;
  const bucketName = `edo-${req.environment}-${req.owning_team}-${req.name}`.toLowerCase();

  const mainTf = `# Generated by idp-portal — do not edit by hand.
# Provisioned via the golden path: pr.yml plans + gates this, apply.yml applies on merge.
# State lives under its own prefix in the shared state bucket, isolating each request.

terraform {
  required_version = ">= 1.5"

  required_providers {
    google = {
      source  = "hashicorp/google"
      version = "~> 6.0"
    }
  }

  backend "gcs" {
    bucket = "${STATE_BUCKET}"
    prefix = "${prefix}"
  }
}

provider "google" {
  project = "${PROJECT_ID}"
  region  = "${REGION}"
}

module "bucket" {
  source = "../../../modules/gcs-bucket"

  name        = "${req.name}"
  owning_team = "${req.owning_team}"
  environment = "${req.environment}"
  request_id  = "${ctx.requestId}"
}

output "bucket_name" {
  description = "Name of the provisioned bucket."
  value       = module.bucket.bucket_name
}
`;

  const metadataYaml = `# Generated by idp-portal — the canonical inventory record for this request.
# The apply pipeline provisions the infrastructure; this file is the durable,
# human-readable source of truth the visibility dashboard (Phase 5) aggregates.
type: gcs-bucket
owning_team: ${req.owning_team}
environment: ${req.environment}
request_id: ${ctx.requestId}
requester: ${ctx.requester}
created_at: "${ctx.date}"
`;

  return {
    stackDir,
    bucketName,
    files: {
      'main.tf': mainTf,
      'metadata.yaml': metadataYaml,
    },
  };
}
