import type { BucketRequest } from './validate';
import { DEFAULT_SETTINGS, type BucketSettings } from './guardrails';

// Pure generator: request + context -> the exact stack files a human would
// hand-write (mirrors idp-gitops/stacks/dev/platform-demo/). No I/O here so it
// is trivially unit-tested; the change drivers are the only side-effecting part.
//
// Every generated stack must be `terraform fmt`-clean, because pr.yml runs
// `fmt -check`. fmt aligns the `=` of consecutive arguments in a block, and the
// optional settings change which key is longest — so the alignment is COMPUTED
// (see `assignments`) rather than baked into the template. A hand-aligned
// template would silently break the moment a caller set a longer key.

// Fixed platform facts (match platform-demo; see CLAUDE.md "Current platform state").
const STATE_BUCKET = 'idp-prototype-edo-tfstate';
const PROJECT_ID = 'idp-prototype-edo';
const REGION = 'europe-west2';

export interface GenerateContext {
  requester: string;
  requestId: string;
  date: string; // YYYY-MM-DD
  settings?: Partial<BucketSettings>;
  /** Set when regenerating an existing stack, so the record says who changed it and when. */
  update?: { by: string; date: string };
}

export interface GeneratedStack {
  stackDir: string; // repo-relative
  bucketName: string;
  files: Record<string, string>;
}

/**
 * Render `key = value` lines the way `terraform fmt` would.
 *
 * fmt aligns the `=` of consecutive single-line arguments, but an argument whose
 * value opens a multi-line block (a map literal) gets exactly one space AND ends
 * the alignment run — so alignment is computed per run of single-line values.
 * Verified against real `terraform fmt -check`; getting this wrong fails
 * pr.yml's `fmt -check` on every generated stack.
 */
function assignments(pairs: Array<[string, string]>, indent: string): string {
  const lines: string[] = [];
  let run: Array<[string, string]> = [];

  const flush = () => {
    if (run.length === 0) return;
    const width = Math.max(...run.map(([k]) => k.length));
    for (const [k, v] of run) lines.push(`${indent}${k.padEnd(width)} = ${v}`);
    run = [];
  };

  for (const [k, v] of pairs) {
    if (v.includes('\n')) {
      flush();
      lines.push(`${indent}${k} = ${v}`);
    } else {
      run.push([k, v]);
    }
  }
  flush();
  return lines.join('\n');
}

function hclString(s: string): string {
  return `"${s.replace(/\\/g, '\\\\').replace(/"/g, '\\"')}"`;
}

/** A single-level HCL map literal, itself internally aligned. */
function hclMap(map: Record<string, string>, indent: string): string {
  const entries = Object.entries(map);
  if (entries.length === 0) return '{}';
  const body = assignments(
    entries.map(([k, v]) => [hclString(k), hclString(v)] as [string, string]),
    `${indent}  `,
  );
  return `{\n${body}\n${indent}}`;
}

export function settingsOf(ctx: GenerateContext): BucketSettings {
  return { ...DEFAULT_SETTINGS, ...(ctx.settings ?? {}) };
}

export function generate(req: BucketRequest, ctx: GenerateContext): GeneratedStack {
  const dirName = `${req.owning_team}-${req.name}`;
  const prefix = `stacks/${req.environment}/${dirName}`;
  const stackDir = `idp-gitops/${prefix}`;
  const bucketName = `edo-${req.environment}-${req.owning_team}-${req.name}`.toLowerCase();
  const settings = settingsOf(ctx);

  // Only non-default settings are written, so a stack stays as small as the
  // request that made it and a PR diff shows exactly what a team asked to change.
  const moduleArgs: Array<[string, string]> = [
    ['name', hclString(req.name)],
    ['owning_team', hclString(req.owning_team)],
    ['environment', hclString(req.environment)],
    ['request_id', hclString(ctx.requestId)],
  ];
  if (settings.retentionDays !== null) moduleArgs.push(['retention_days', String(settings.retentionDays)]);
  if (settings.storageClass !== DEFAULT_SETTINGS.storageClass) moduleArgs.push(['storage_class', hclString(settings.storageClass)]);
  if (Object.keys(settings.extraLabels).length > 0) moduleArgs.push(['extra_labels', hclMap(settings.extraLabels, '  ')]);

  const mainTf = `# Generated by the IDP platform — do not edit by hand.
# Provisioned via the golden path: pr.yml plans + gates this, apply.yml applies on merge.
# State lives under its own prefix in the shared state bucket, isolating each request.

terraform {
  required_version = ">= 1.5"

  required_providers {
    google = {
      source  = "hashicorp/google"
      version = "~> 6.0"
    }
  }

  backend "gcs" {
    bucket = "${STATE_BUCKET}"
    prefix = "${prefix}"
  }
}

provider "google" {
  project = "${PROJECT_ID}"
  region  = "${REGION}"
}

module "bucket" {
  source = "../../../modules/gcs-bucket"

${assignments(moduleArgs, '  ')}
}

output "bucket_name" {
  description = "Name of the provisioned bucket."
  value       = module.bucket.bucket_name
}
`;

  // The settings block is recorded so the inventory can report what a bucket is
  // actually set to without parsing Terraform. Git history is the change log —
  // this file only needs to say what is true now, and who last changed it.
  const settingsYaml = [
    'settings:',
    `  retention_days: ${settings.retentionDays === null ? 'null' : settings.retentionDays}`,
    `  storage_class: ${settings.storageClass}`,
    Object.keys(settings.extraLabels).length === 0
      ? '  extra_labels: {}'
      : ['  extra_labels:', ...Object.entries(settings.extraLabels).map(([k, v]) => `    ${k}: ${v}`)].join('\n'),
  ].join('\n');

  const updatedYaml = ctx.update ? `updated_at: "${ctx.update.date}"\nupdated_by: ${ctx.update.by}\n` : '';

  const metadataYaml = `# Generated by the IDP platform — the canonical inventory record for this request.
# The apply pipeline provisions the infrastructure; this file is the durable,
# human-readable source of truth the visibility dashboard (Phase 5) aggregates.
type: gcs-bucket
owning_team: ${req.owning_team}
environment: ${req.environment}
request_id: ${ctx.requestId}
requester: ${ctx.requester}
created_at: "${ctx.date}"
${updatedYaml}${settingsYaml}
`;

  return {
    stackDir,
    bucketName,
    files: {
      'main.tf': mainTf,
      'metadata.yaml': metadataYaml,
    },
  };
}
