# Generated by idp-portal — do not edit by hand.
# Provisioned via the golden path: pr.yml plans + gates this, apply.yml applies on merge.
# State lives under its own prefix in the shared state bucket, isolating each request.

terraform {
  required_version = ">= 1.5"

  required_providers {
    google = {
      source  = "hashicorp/google"
      version = "~> 6.0"
    }
  }

  backend "gcs" {
    bucket = "idp-prototype-edo-tfstate"
    prefix = "stacks/dev/payments-discounts"
  }
}

provider "google" {
  project = "idp-prototype-edo"
  region  = "europe-west2"
}

module "bucket" {
  source = "../../../modules/gcs-bucket"

  name        = "discounts"
  owning_team = "payments"
  environment = "dev"
  request_id  = "req-20260903-payments-discounts-z0of"
}

output "bucket_name" {
  description = "Name of the provisioned bucket."
  value       = module.bucket.bucket_name
}
