# First hand-written stack — proves the golden path end to end:
#   PR  -> pr.yml plans this and comments the plan
#   merge -> apply.yml provisions a real, compliant bucket via WIF
#
# Later stacks are generated by the portal (Phase 3); this one is authored by
# hand to validate the pattern. State lives under its own prefix in the shared
# state bucket, isolating each request.

terraform {
  required_version = ">= 1.5"

  required_providers {
    google = {
      source  = "hashicorp/google"
      version = "~> 6.0"
    }
  }

  backend "gcs" {
    bucket = "idp-prototype-edo-tfstate"
    prefix = "stacks/dev/platform-demo"
  }
}

provider "google" {
  project = "idp-prototype-edo"
  region  = "europe-west2"
}

module "bucket" {
  source = "../../../modules/gcs-bucket"

  name        = "demo"
  owning_team = "platform"
  environment = "dev"
  request_id  = "req-20260829-platform-demo"
}

output "bucket_name" {
  description = "Name of the provisioned bucket."
  value       = module.bucket.bucket_name
}
