/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/buckets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List buckets
         * @description The inventory, read straight from the GitOps repo: every stack's `metadata.yaml`. There
         *     is no database — the repo *is* the inventory, so this can never disagree with what is
         *     actually declared.
         */
        get: operations["listBuckets"];
        put?: never;
        /**
         * Request a new bucket
         * @description Generates the Terraform stack a human would have hand-written and opens it as a change
         *     request. Nothing is provisioned until the request is reviewed, passes the policy gate
         *     and is merged.
         *
         *     The bucket name is **derived**, not chosen: `edo-{environment}-{owningTeam}-{name}`.
         */
        post: operations["createBucket"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/buckets/{bucketId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The derived, globally unique bucket name. */
                bucketId: components["parameters"]["BucketId"];
            };
            cookie?: never;
        };
        /**
         * Describe a bucket
         * @description The full record: ownership and provenance, the guardrails the platform enforces on it,
         *     the settings that can be changed, and any change request currently in flight.
         */
        get: operations["describeBucket"];
        put?: never;
        post?: never;
        /**
         * Decommission a bucket
         * @description Opens a change request that removes the stack. On merge the destroy pipeline tears the
         *     bucket down and the inventory record goes with it.
         *
         *     The bucket is **not** deleted by this call — it is deleted when the request is merged.
         *     The module sets `force_destroy = false`, so a non-empty bucket fails the destroy rather
         *     than discarding data.
         */
        delete: operations["deleteBucket"];
        options?: never;
        head?: never;
        /**
         * Change a bucket's mutable settings
         * @description Only the settings under `BucketUpdate` can change. Identity (`name`, `owningTeam`,
         *     `environment`) is immutable because the bucket name is derived from it — changing one
         *     would destroy and recreate the bucket and lose its data, so the platform refuses rather
         *     than silently doing that. Move data to a new bucket instead.
         *
         *     Omitted fields are left as they are; an explicit `null` resets a field to the platform
         *     default.
         */
        patch: operations["updateBucket"];
        trace?: never;
    };
    "/v1/requests": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List change requests in flight
         * @description Open change requests — everything requested but not yet provisioned.
         */
        get: operations["listRequests"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/requests/{requestId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get a change request's status
         * @description Resolved live from the GitOps repo — review state, the policy gate's verdict and the
         *     apply outcome. There is no request database, so this cannot drift from reality.
         */
        get: operations["getRequest"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/catalog/teams": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List the teams that can own a resource
         * @description From `platform/teams.yaml` — the same registry the Terraform module validates against.
         */
        get: operations["listTeams"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/catalog/environments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List the deployable environments */
        get: operations["listEnvironments"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Delivery metrics
         * @description Aggregated on demand from the GitHub API: apply success rate and lead time from request
         *     to provisioned. The same numbers the oversight dashboard renders.
         */
        get: operations["getMetrics"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/compliance": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Compliance and drift status
         * @description Policy-gate pass rate and any buckets whose real state has drifted from what is declared.
         */
        get: operations["getCompliance"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness probe */
        get: operations["health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description The derived bucket name, `{orgPrefix}-{environment}-{owningTeam}-{name}`.
         * @example edo-dev-checkout-orders
         */
        BucketId: string;
        /**
         * @description Unique id for a change request, also written as the bucket's `request-id` label.
         * @example req-20260905-checkout-orders-a1b2
         */
        RequestId: string;
        /**
         * @description A deployable environment, from `platform/config.yaml`.
         * @enum {string}
         */
        Environment: "dev" | "test" | "prod";
        /**
         * @description The sanctioned storage classes. Restricted to classes with no minimum-storage-duration
         *     billing surprise for a self-service golden path.
         * @default STANDARD
         * @enum {string}
         */
        StorageClass: "STANDARD" | "NEARLINE";
        /**
         * @description Extra labels for cost attribution or ownership context. The platform's own labels
         *     (`owning-team`, `environment`, `managed-by`, `request-id`) are reserved and cannot be
         *     set or overridden here.
         * @example {
         *       "cost-centre": "cc-1234"
         *     }
         */
        LabelMap: {
            [key: string]: string;
        };
        Team: {
            /** @example checkout */
            id: string;
            /** @example Checkout */
            name: string;
        };
        /**
         * @description What the platform enforces on every bucket and no client can override. Returned so a
         *     caller can see the compliance posture it inherited without reading Terraform. Enforced
         *     in the module and re-checked independently by the policy gate.
         */
        Guardrails: {
            /** @example europe-west2 */
            location: string;
            /** @constant */
            uniformBucketLevelAccess: true;
            /** @constant */
            publicAccessPrevention: "enforced";
            /** @constant */
            versioning: true;
            /** @constant */
            forceDestroy: false;
        };
        /** @description The knobs a team may actually turn. Everything else is platform-enforced. */
        BucketSettings: {
            /**
             * @description Delete noncurrent object versions after this many days. Null means keep them
             *     indefinitely (the default).
             * @example 30
             */
            retentionDays?: number | null;
            storageClass?: components["schemas"]["StorageClass"];
            extraLabels?: components["schemas"]["LabelMap"];
        };
        Bucket: {
            bucketId: components["schemas"]["BucketId"];
            /**
             * @description The short name the developer chose; the trailing segment of `bucketId`.
             * @example orders
             */
            name: string;
            environment: components["schemas"]["Environment"];
            /** @example checkout */
            owningTeam: string;
            /** @example gcs-bucket */
            type: string;
            requestId: components["schemas"]["RequestId"];
            /**
             * @description GitHub handle of whoever requested it.
             * @example octocat
             */
            requester: string;
            /**
             * Format: date
             * @example 2026-09-05
             */
            createdAt: string;
            /**
             * @description Where this bucket is declared in the GitOps repo.
             * @example idp-gitops/stacks/dev/checkout-orders
             */
            stackDir: string;
            guardrails: components["schemas"]["Guardrails"];
            settings: components["schemas"]["BucketSettings"];
            /** @description A change request currently in flight against this bucket, if any. */
            pendingRequest?: components["schemas"]["Request"] | null;
        };
        /**
         * @description The developer picks four things; the platform decides everything else. That is the
         *     golden path — the smallest choice surface that still leaves a team in control of what
         *     matters.
         */
        BucketCreate: {
            /**
             * @description Short name; combined with environment and team into the bucket name.
             * @example orders
             */
            name: string;
            /**
             * @description Must be a team in `platform/teams.yaml`.
             * @example checkout
             */
            owningTeam: string;
            environment: components["schemas"]["Environment"];
            /**
             * @description GitHub handle to record as the requester. For an automated caller, the handle of
             *     the bot or the team it acts for — the inventory should always name someone
             *     accountable.
             * @example octocat
             */
            requester: string;
            settings?: components["schemas"]["BucketSettings"];
        };
        /**
         * @description A sparse patch of the mutable settings. Supplying an immutable field (`name`,
         *     `owningTeam`, `environment`) is rejected with 400 rather than ignored, so a client is
         *     never silently misled about what changed.
         */
        BucketUpdate: components["schemas"]["BucketSettings"];
        /** @enum {string} */
        RequestIntent: "create" | "update" | "delete";
        /**
         * @description Where a change request has got to.
         *
         *     | status | meaning |
         *     |---|---|
         *     | `pending_review` | Open; checks running or passed. Waiting on a human. |
         *     | `blocked` | Open, but the policy gate or plan failed. Needs a fix, not a review. |
         *     | `merged` | Approved and merged; provisioning is running. |
         *     | `applied` | Provisioned. The resource is live. |
         *     | `decommissioned` | Torn down; the inventory record is gone. |
         *     | `failed` | Merged, but the apply or destroy failed. Needs attention. |
         *     | `cancelled` | Closed without merging. Nothing changed. |
         *
         *     `applied`, `decommissioned`, `failed` and `cancelled` are terminal.
         * @enum {string}
         */
        RequestStatus: "pending_review" | "blocked" | "merged" | "applied" | "decommissioned" | "failed" | "cancelled";
        /** @description An auditable change moving through review, the policy gate and apply. */
        Request: {
            requestId: components["schemas"]["RequestId"];
            intent: components["schemas"]["RequestIntent"];
            status: components["schemas"]["RequestStatus"];
            bucketId: components["schemas"]["BucketId"];
            /** @example idp-gitops/stacks/dev/checkout-orders */
            stackDir: string;
            /** Format: date-time */
            submittedAt: string;
            /**
             * @description Why the request is where it is — the gate's objection when `blocked`, the failure
             *     when `failed`. Human-readable; do not parse it.
             */
            message?: string;
            /**
             * @description Where to go to see or act on this change. The one place the underlying mechanism
             *     surfaces, because a human needs a link to click.
             */
            review: {
                /**
                 * Format: uri
                 * @description The change to review.
                 */
                url: string;
                /** @description Its number in the review system. */
                number?: number;
            };
        };
        /** @description Exactly what a real call would have committed. */
        DryRunResult: {
            intent: components["schemas"]["RequestIntent"];
            bucketId: components["schemas"]["BucketId"];
            stackDir: string;
            /**
             * @description One-line description of the change.
             * @example create idp-gitops/stacks/dev/checkout-orders (2 files)
             */
            summary: string;
            /** @description The files the change would write. A null `content` means the file is removed. */
            files: {
                /** @example idp-gitops/stacks/dev/checkout-orders/main.tf */
                path: string;
                content: string | null;
            }[];
        };
        /**
         * @description How well the platform is serving its users. Nulls mean "not enough data yet" and are
         *     deliberately not zero — an unmeasured platform should say so rather than look perfect.
         */
        DeliveryMetrics: {
            /** @description Completed provisioning runs observed. */
            applyRuns: number;
            applySuccess: number;
            applySuccessRate: number | null;
            /** @description Median minutes from request to provisioned. */
            medianLeadTimeMins: number | null;
            recent: {
                number: number;
                title: string;
                /** Format: date-time */
                createdAt: string;
                /** Format: date-time */
                mergedAt: string | null;
                leadTimeMins: number | null;
                /** Format: uri */
                url: string;
            }[];
        };
        Compliance: {
            /**
             * @description Buckets whose real state no longer matches what is declared — someone changed them
             *     outside the platform.
             */
            openDrift: {
                stack: string;
                issueNumber: number;
                /** Format: uri */
                url: string;
            }[];
            policyRuns: number;
            policyPass: number;
            policyPassRate: number | null;
        };
        /** @description An error, in the RFC 9457 `application/problem+json` shape. */
        Problem: {
            /**
             * Format: uri-reference
             * @description Identifies the kind of problem.
             * @default about:blank
             * @example /problems/validation-failed
             */
            type: string;
            /** @example Validation failed */
            title: string;
            status: number;
            /** @description What went wrong with this specific request. */
            detail?: string;
            /** Format: uri-reference */
            instance?: string;
            /** @description Field-level failures, so a client can attribute each one to its input. */
            errors?: {
                /** @example name */
                field: string;
                message: string;
            }[];
        };
    };
    responses: {
        /** @description The change request was opened. Nothing is provisioned yet — follow `Location` for status. */
        RequestAccepted: {
            headers: {
                /** @description The change request to poll. */
                Location?: string;
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Request"];
            };
        };
        /** @description What would be committed. Nothing was opened. */
        DryRun: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["DryRunResult"];
            };
        };
        /**
         * @description The request is malformed or violates a platform convention. `errors` names the offending
         *     fields so a client can point at them individually.
         */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description A GitHub bearer token is required, or the one supplied was rejected. */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description No such resource. */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /**
         * @description Another change request is already open against this bucket. Merge or close it first —
         *     the platform allows one writer at a time so two changes cannot race on shared state.
         */
        RequestInFlight: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description The GitHub API could not be reached, so the aggregate could not be computed. */
        UpstreamUnavailable: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
    };
    parameters: {
        /** @description The derived, globally unique bucket name. */
        BucketId: components["schemas"]["BucketId"];
        /**
         * @description Render the change and return exactly what would be committed, without opening anything.
         *     The reviewable diff, before there is a request to review.
         */
        DryRun: boolean;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listBuckets: {
        parameters: {
            query?: {
                /** @description Only buckets in this environment. */
                environment?: components["schemas"]["Environment"];
                /** @description Only buckets owned by this team id. */
                team?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The matching buckets. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        buckets: components["schemas"]["Bucket"][];
                    };
                };
            };
            400: components["responses"]["BadRequest"];
        };
    };
    createBucket: {
        parameters: {
            query?: {
                /**
                 * @description Render the change and return exactly what would be committed, without opening anything.
                 *     The reviewable diff, before there is a request to review.
                 */
                dryRun?: components["parameters"]["DryRun"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BucketCreate"];
            };
        };
        responses: {
            200: components["responses"]["DryRun"];
            202: components["responses"]["RequestAccepted"];
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            /**
             * @description A bucket with this derived name already exists, or another change request is
             *     already in flight against it.
             */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    describeBucket: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The derived, globally unique bucket name. */
                bucketId: components["parameters"]["BucketId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The bucket. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Bucket"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    deleteBucket: {
        parameters: {
            query?: {
                /**
                 * @description Render the change and return exactly what would be committed, without opening anything.
                 *     The reviewable diff, before there is a request to review.
                 */
                dryRun?: components["parameters"]["DryRun"];
            };
            header?: never;
            path: {
                /** @description The derived, globally unique bucket name. */
                bucketId: components["parameters"]["BucketId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["DryRun"];
            202: components["responses"]["RequestAccepted"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["RequestInFlight"];
        };
    };
    updateBucket: {
        parameters: {
            query?: {
                /**
                 * @description Render the change and return exactly what would be committed, without opening anything.
                 *     The reviewable diff, before there is a request to review.
                 */
                dryRun?: components["parameters"]["DryRun"];
            };
            header?: never;
            path: {
                /** @description The derived, globally unique bucket name. */
                bucketId: components["parameters"]["BucketId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BucketUpdate"];
            };
        };
        responses: {
            200: components["responses"]["DryRun"];
            202: components["responses"]["RequestAccepted"];
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["RequestInFlight"];
        };
    };
    listRequests: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The open change requests. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        requests: components["schemas"]["Request"][];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    getRequest: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                requestId: components["schemas"]["RequestId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The change request. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Request"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    listTeams: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The known teams. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        teams: components["schemas"]["Team"][];
                    };
                };
            };
        };
    };
    listEnvironments: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The known environments and platform-wide conventions. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        environments: components["schemas"]["Environment"][];
                        /** @example edo */
                        orgPrefix: string;
                        /** @example europe-west2 */
                        region: string;
                    };
                };
            };
        };
    };
    getMetrics: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Delivery metrics. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeliveryMetrics"];
                };
            };
            401: components["responses"]["Unauthorized"];
            502: components["responses"]["UpstreamUnavailable"];
        };
    };
    getCompliance: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Compliance status. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Compliance"];
                };
            };
            401: components["responses"]["Unauthorized"];
            502: components["responses"]["UpstreamUnavailable"];
        };
    };
    health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The service is up. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        status: "ok";
                    };
                };
            };
        };
    };
}
