import { describe, it, expect } from 'vitest';
import { generate } from '../src/generator';
import { generateRequestId } from '../src/requestId';

const ctx = { requester: 'edoatley', requestId: 'req-20260829-platform-demo', date: '2026-08-29' };

const EXPECTED_MAIN_TF = `# Generated by the IDP platform — do not edit by hand.
# Provisioned via the golden path: pr.yml plans + gates this, apply.yml applies on merge.
# State lives under its own prefix in the shared state bucket, isolating each request.

terraform {
  required_version = ">= 1.5"

  required_providers {
    google = {
      source  = "hashicorp/google"
      version = "~> 6.0"
    }
  }

  backend "gcs" {
    bucket = "idp-prototype-edo-tfstate"
    prefix = "stacks/dev/platform-demo"
  }
}

provider "google" {
  project = "idp-prototype-edo"
  region  = "europe-west2"
}

module "bucket" {
  source = "../../../modules/gcs-bucket"

  name        = "demo"
  owning_team = "platform"
  environment = "dev"
  request_id  = "req-20260829-platform-demo"
}

output "bucket_name" {
  description = "Name of the provisioned bucket."
  value       = module.bucket.bucket_name
}
`;

const EXPECTED_METADATA = `# Generated by the IDP platform — the canonical inventory record for this request.
# The apply pipeline provisions the infrastructure; this file is the durable,
# human-readable source of truth the visibility dashboard (Phase 5) aggregates.
type: gcs-bucket
owning_team: platform
environment: dev
request_id: req-20260829-platform-demo
requester: edoatley
created_at: "2026-08-29"
settings:
  retention_days: null
  storage_class: STANDARD
  extra_labels: {}
`;

describe('generate', () => {
  const out = generate({ name: 'demo', owning_team: 'platform', environment: 'dev' }, ctx);

  it('places the stack under stacks/<env>/<team>-<name>', () => {
    expect(out.stackDir).toBe('idp-gitops/stacks/dev/platform-demo');
  });

  it('derives the deterministic bucket name', () => {
    expect(out.bucketName).toBe('edo-dev-platform-demo');
  });

  it('generates main.tf matching the platform-demo template (fmt-clean)', () => {
    expect(out.files['main.tf']).toBe(EXPECTED_MAIN_TF);
  });

  it('generates the metadata.yaml inventory record', () => {
    expect(out.files['metadata.yaml']).toBe(EXPECTED_METADATA);
  });

  it('calls the module by relative source with the right backend prefix', () => {
    expect(out.files['main.tf']).toContain('source = "../../../modules/gcs-bucket"');
    expect(out.files['main.tf']).toContain('prefix = "stacks/dev/platform-demo"');
  });
});

describe('generateRequestId', () => {
  it('is deterministic with injected date + suffix and in the label charset', () => {
    const id = generateRequestId('checkout', 'orders', { date: new Date('2026-08-31T00:00:00Z'), suffix: () => 'ab12' });
    expect(id).toBe('req-20260831-checkout-orders-ab12');
    expect(id).toMatch(/^[a-z0-9_-]{1,63}$/);
  });
});

// The generated stack must be `terraform fmt`-clean or pr.yml's `fmt -check`
// fails on every request. fmt aligns runs of single-line arguments and gives an
// argument opening a multi-line block a single space — these tests pin both,
// because the alignment is computed and a regression here breaks the pipeline
// rather than any test that only checks values.
describe('generate with mutable settings', () => {
  const base = { name: 'orders', owning_team: 'checkout', environment: 'dev' } as const;
  const settingsCtx = { requester: 'octocat', requestId: 'req-20260905-checkout-orders-a1b2', date: '2026-09-05' };

  it('omits settings left at the platform default, keeping the stack minimal', () => {
    const out = generate(base, settingsCtx);
    expect(out.files['main.tf']).not.toContain('retention_days');
    expect(out.files['main.tf']).not.toContain('storage_class');
    expect(out.files['main.tf']).not.toContain('extra_labels');
  });

  it('realigns the whole module block when a longer key appears', () => {
    const out = generate(base, { ...settingsCtx, settings: { retentionDays: 30 } });
    expect(out.files['main.tf']).toContain(
      [
        '  name           = "orders"',
        '  owning_team    = "checkout"',
        '  environment    = "dev"',
        '  request_id     = "req-20260905-checkout-orders-a1b2"',
        '  retention_days = 30',
      ].join('\n'),
    );
  });

  it('gives a map-valued argument a single space and aligns the map internally', () => {
    const out = generate(base, {
      ...settingsCtx,
      settings: { retentionDays: 365, storageClass: 'NEARLINE', extraLabels: { 'cost-centre': 'cc-1', x: 'y' } },
    });
    expect(out.files['main.tf']).toContain(
      [
        '  retention_days = 365',
        '  storage_class  = "NEARLINE"',
        '  extra_labels = {',
        '    "cost-centre" = "cc-1"',
        '    "x"           = "y"',
        '  }',
      ].join('\n'),
    );
  });

  it('records the settings in metadata.yaml so the inventory can report them', () => {
    const out = generate(base, { ...settingsCtx, settings: { retentionDays: 30, extraLabels: { 'cost-centre': 'cc-1' } } });
    expect(out.files['metadata.yaml']).toContain(
      ['settings:', '  retention_days: 30', '  storage_class: STANDARD', '  extra_labels:', '    cost-centre: cc-1'].join('\n'),
    );
  });

  it('records who changed an existing stack, and when', () => {
    const out = generate(base, { ...settingsCtx, update: { by: 'ravi-menon', date: '2026-09-06' } });
    expect(out.files['metadata.yaml']).toContain('updated_at: "2026-09-06"\nupdated_by: ravi-menon');
    // The original requester and creation date are provenance — never rewritten.
    expect(out.files['metadata.yaml']).toContain('requester: octocat');
    expect(out.files['metadata.yaml']).toContain('created_at: "2026-09-05"');
  });
});
