import { describe, it, expect } from 'vitest';
import { generate } from '../src/generator';
import { generateRequestId } from '../src/requestId';

const ctx = { requester: 'edoatley', requestId: 'req-20260829-platform-demo', date: '2026-08-29' };

const EXPECTED_MAIN_TF = `# Generated by idp-portal — do not edit by hand.
# Provisioned via the golden path: pr.yml plans + gates this, apply.yml applies on merge.
# State lives under its own prefix in the shared state bucket, isolating each request.

terraform {
  required_version = ">= 1.5"

  required_providers {
    google = {
      source  = "hashicorp/google"
      version = "~> 6.0"
    }
  }

  backend "gcs" {
    bucket = "idp-prototype-edo-tfstate"
    prefix = "stacks/dev/platform-demo"
  }
}

provider "google" {
  project = "idp-prototype-edo"
  region  = "europe-west2"
}

module "bucket" {
  source = "../../../modules/gcs-bucket"

  name        = "demo"
  owning_team = "platform"
  environment = "dev"
  request_id  = "req-20260829-platform-demo"
}

output "bucket_name" {
  description = "Name of the provisioned bucket."
  value       = module.bucket.bucket_name
}
`;

const EXPECTED_METADATA = `# Generated by idp-portal — the canonical inventory record for this request.
# The apply pipeline provisions the infrastructure; this file is the durable,
# human-readable source of truth the visibility dashboard (Phase 5) aggregates.
type: gcs-bucket
owning_team: platform
environment: dev
request_id: req-20260829-platform-demo
requester: edoatley
created_at: "2026-08-29"
`;

describe('generate', () => {
  const out = generate({ name: 'demo', owning_team: 'platform', environment: 'dev' }, ctx);

  it('places the stack under stacks/<env>/<team>-<name>', () => {
    expect(out.stackDir).toBe('idp-gitops/stacks/dev/platform-demo');
  });

  it('derives the deterministic bucket name', () => {
    expect(out.bucketName).toBe('edo-dev-platform-demo');
  });

  it('generates main.tf matching the platform-demo template (fmt-clean)', () => {
    expect(out.files['main.tf']).toBe(EXPECTED_MAIN_TF);
  });

  it('generates the metadata.yaml inventory record', () => {
    expect(out.files['metadata.yaml']).toBe(EXPECTED_METADATA);
  });

  it('calls the module by relative source with the right backend prefix', () => {
    expect(out.files['main.tf']).toContain('source = "../../../modules/gcs-bucket"');
    expect(out.files['main.tf']).toContain('prefix = "stacks/dev/platform-demo"');
  });
});

describe('generateRequestId', () => {
  it('is deterministic with injected date + suffix and in the label charset', () => {
    const id = generateRequestId('checkout', 'orders', { date: new Date('2026-08-31T00:00:00Z'), suffix: () => 'ab12' });
    expect(id).toBe('req-20260831-checkout-orders-ab12');
    expect(id).toMatch(/^[a-z0-9_-]{1,63}$/);
  });
});
